#!/bin/bash

my_dir="$(dirname "$(realpath "$0")")"

fragment_outfile="${1:-$my_dir/src/com/aicp/extras/search/AeFragmentList.java}"
manifest_outfile="${2:-$my_dir/AndroidManifest.xml}"

disclaimer="/* Do not touch! Auto-generated by $(basename "$0")*/"

# Matches SettingsActivity.AE_FRAGMENT_ACTION_PREFIX
intent_action_prefix="com.aicp.extras.fragmentaction"

get_xml_root_string() {
    file="$1"
    attr="$2"
    if [ ! -f "$file" ]; then
        return
    fi
    output="$(echo -e "setns android=http://schemas.android.com/apk/res/android\ncat /PreferenceScreen/@$attr" | xmllint "$file" --shell 2>/dev/null)"
    content="$(echo "$output" | grep "$attr=")"
    if [ $? -eq 0 ]; then
        echo "$content" | sed "s/.*$attr=//" | sed 's/"//g'
    fi
}

string_ref_xml_to_java() {
    echo "$1" | sed 's|@string/|R.string.|'
}

components=""
actions=""

shopt -s nullglob
fragment_files=("$my_dir/src/com/aicp/extras/fragments/"*.kt "$my_dir/src/com/aicp/extras/fragments/"*.java)
shopt -u nullglob

for fragment in "${fragment_files[@]}"; do
    fragment_file="$(basename "$fragment")"
    fragment_short="${fragment_file%.*}"
    fragment_full="com.aicp.extras.fragments.$fragment_short"

    # Capture up to 2 lines following getPreferenceResource to handle newlines after '=' or '{ return'
    xmlres="$(grep -A 2 "getPreferenceResource" "$fragment" | grep -o 'R\.xml\.[a-zA-Z0-9_]*' | head -n 1)"
    if [ -n "$xmlres" ]; then
        xml_name="${xmlres#R.xml.}"
        xmlfile="$my_dir/res/xml/${xml_name}.xml"
        title="$(get_xml_root_string "$xmlfile" "android:title")"
        summary="$(get_xml_root_string "$xmlfile" "android:summary")"
        if [ -z "$title" ]; then
            >&2 echo "Could not find title in $xmlfile"
        else
            key="$(get_xml_root_string "$xmlfile" "android:key")"
            title="$(string_ref_xml_to_java "$title")"
            if [ -z "$summary" ]; then
                summary=0
            else
                summary="$(string_ref_xml_to_java "$summary")"
            fi
            echo "Adding $fragment_short to searchables"
            components="$components\n        new AeFragmentInfo(\"$fragment_full\", \"$key\", $title, $summary, $xmlres),"
            actions="$actions\n                <action android:name=\"$intent_action_prefix.$fragment_full\" />"
        fi
    else
        if grep -q "getPreferenceResource" "$fragment"; then
            >&2 echo "Could not find xml resource for $fragment_full"
        fi
    fi
done

if [ -f "$my_dir/AeFragmentList.java" ]; then
    sed -e "s|/\* xx0xx \*/|$disclaimer|" -e "s|/\* xx1xx \*/|$components|" "$my_dir/AeFragmentList.java" > "$fragment_outfile"
fi

# Only attempt manifest modification if running standalone outside Soong/genrule
if [ -n "$2" ] && [ "$2" != "AndroidManifest.xml" ] && [ -f "$2" ]; then
    sed "s|<!-- xx1xx -->|<!-- automated content: -->$actions\n                <!-- xx1xx -->|" "$my_dir/AndroidManifest.xml" > "$2"
elif [ -z "$1" ] && [ -f "$my_dir/AndroidManifest.xml" ]; then
    # Standalone execution in source tree
    sed -i "s|<!-- xx1xx -->|<!-- automated content: -->$actions\n                <!-- xx1xx -->|" "$my_dir/AndroidManifest.xml"
fi
